### ISSUE TITLE
SyntaxError due to malformed INFO lines

### ISSUE THREAD

**Issue by trutane** [jamescasbon/PyVCF#192]
If whitespace is present after the commas in the key=value attribute list for an INFO metadata line in a VCF, such as:

`##INFO=<ID=VP, Number=1, Type=String, Description="Variation Property.  Documentation is at ftp://ftp.ncbi.nlm.nih.gov/snp/specs/dbSNP_BitField_latest.pdf">`

this will cause PyVCF to exit with a SyntaxError:

```python
  File ".../apps/python-2.7.3/lib/python2.7/site-packages/PyVCF-0.6.6-py2.7.egg/vcf/parser.py", line 288, in __init__
    self._parse_metainfo()
  File ".../apps/python-2.7.3/lib/python2.7/site-packages/PyVCF-0.6.6-py2.7.egg/vcf/parser.py", line 309, in _parse_metainfo
    key, val = parser.read_info(line)
  File ".../apps/python-2.7.3/lib/python2.7/site-packages/PyVCF-0.6.6-py2.7.egg/vcf/parser.py", line 123, in read_info
    "One of the INFO lines is malformed: %s" % info_string)
SyntaxError: One of the INFO lines is malformed: ##INFO=<ID=VP, Number=1, Type=String, Description="Variation Property.  Documentation is at ftp://ftp.ncbi.nlm.nih.gov/snp/specs/dbSNP_BitField_latest.pdf">
```

Without whitespace, no problem:
`##INFO=<ID=VP,Number=1,Type=String,Description="Variation Property.  Documentation is at ftp://ftp.ncbi.nlm.nih.gov/snp/specs/dbSNP_BitField_latest.pdf">`

The [VCF spec](http://samtools.github.io/hts-specs/VCFv4.2.pdf) does not explicitly forbid whitespace in between the key=value pairs in the INFO lines, so it seems like overkill to abort parsing due to this.

This issue affects VCF files produced by SnpEff/SnpSift v4.1b.

**Comment by martijnvermaat** [comment]
Thanks @trutane for reporting. The VCF spec is unclear on this, so considering tools are producing this, let's allow it.

**Comment by JKosmicki** [comment]
While the VCF spec is unclear on this issue, GATK which many of us I imagine use is explicit in forbidding whitespaces in the INFO field.  I found this out when I used VEP to add the PolyPhen2 annotations to the INFO field and GATK threw an error because `Probably Damaging` and `Possibly Damaging` have spaces in them.  I believe VEP has fixed this and not uses an underline.

So long story short, while it is worth allowing for whitespaces, I feel that if one rewrites the VCF, it should definitely eliminate any whitespaces in the output.

**Comment by martijnvermaat** [comment]
@JKosmicki While we now allow for whitespace here, it is not preserved. I agree it is best to be conservative, especially when writing.

If, however, you're having problems parsing certain files with GATK that are not strictly in violation of the spec, you might want to file a bug report on GATK.
