### ISSUE TITLE
How does PyVCF handle entry collision in INFO tab?

### ISSUE THREAD

**Issue by kotoroshinoto** [jamescasbon/PyVCF#221]
It appears to construct a dict of the entries in INFO, I was hoping to use PyVCF to interact with the COSMIC VCF files, but they have many entries with duplicate INFO tags.
such as: 

GENE=OR4F5;STRAND=+;GENE=OR4F5;STRAND=+;CDS=c.134A>C;AA=p.D45A;CNT=1

I'm not sure WHY they format their file like this. I don't currently know if it means anything or if there are any cases where the values don't match. How would PyVCF handle this?

**Comment by martijnvermaat** [comment]
Hi @kotoroshinoto, the short answer is that PyVCF only uses the right-most value for a given key.

I don't think the example you give is valid use of the INFO column. I had a quick look at the complete COSMIC data myself and the VCF header simply states that `GENE` and `STRAND` are singular string values:

    ##INFO=<ID=GENE,Number=1,Type=String,Description="Gene name">
    ##INFO=<ID=STRAND,Number=1,Type=String,Description="Gene strand">

Also, it seems that the two values always have the exact same value (I only checked `/files/grch38/cosmic/v75/VCF/CosmicCodingMuts.vcf.gz`). In that case you should be fine with the current behaviour of PyVCF, but I have no clue why the values are duplicated.

I'll close this issue now, since it doesn't look like a bug in PyVCF. If you have any further questions or problems feel free to re-open or comment.
